/* Conteúdo extraído do portfólio atual (tecnologiaseducacionais.senai.br).
   "aud" (público) e "plat" (plataformas) foram inferidos a partir das descrições — revisar com o time de produto. */
window.CATS = [
  { id: "cursos",    name: "Aprender",   long: "Plataformas de Cursos",            icon: "school",         hue: "#9d2600", blurb: "Minicursos, microcursos e cursos técnicos a um clique." },
  { id: "eco",       name: "Conectar",   long: "Ecossistemas",                     icon: "hub",            hue: "#3d5aaa", blurb: "Portais que reúnem as plataformas do SENAI." },
  { id: "praticas",  name: "Ensinar",    long: "Práticas Pedagógicas",             icon: "menu_book",      hue: "#c4380d", blurb: "Itinerários, recursos didáticos, livros e ferramentas criativas." },
  { id: "avaliacao", name: "Avaliar",    long: "Sistemas de Avaliações",           icon: "fact_check",     hue: "#224291", blurb: "Bancos de itens, provas e avaliação prática." },
  { id: "imersao",   name: "Imergir",    long: "Tecnologias Imersivas e Simuladores", icon: "view_in_ar",  hue: "#882000", blurb: "Realidade virtual, mista e aumentada para praticar com segurança." },
  { id: "gestao",    name: "Gerir",      long: "Sistemas de Gestão",               icon: "monitoring",     hue: "#183a89", blurb: "Indicadores, pesquisas, empregos e recompensas." },
  { id: "inovacao",  name: "Inovar",     long: "Inovação",                         icon: "lightbulb",      hue: "#b22c00", blurb: "Plataformas para ideias e competições." },
  { id: "assistiva", name: "Incluir",    long: "Tecnologias Assistivas",           icon: "accessibility_new", hue: "#3d5aaa", blurb: "Acessibilidade para uma educação de todos." }
];

window.AUD = { aluno: "Alunos", docente: "Docentes", gestor: "Gestão", empresa: "Empresas" };

window.TECHS = [
  // ---------- Aprender
  { id: "senai-play", cat: "cursos", name: "SENAI Play", kicker: "Minicursos e microcursos", featured: true,
    desc: "Iniciativa do SENAI que traz inovação tecnológica na forma de aprender: conhecimento em doses compactas, em minicursos e microcursos de vários segmentos da indústria. Foi projetado para ser acessível e está disponível em dispositivos móveis.",
    aud: ["aluno"], plat: ["Web", "Mobile"],
    links: [{ label: "Acessar plataforma", url: "https://play.senai.br/", primary: true }, { label: "Conhecer em vídeo", url: "https://www.youtube.com/watch?v=iZrkpTHq2xQ" }] },
  { id: "play-business", cat: "cursos", name: "SENAI Play Business", kicker: "Microcursos para empresas",
    desc: "Extensão do SENAI Play criada para levar educação profissional de alta qualidade aos colaboradores de empresas industriais. Com a assinatura, o time acessa todo o portfólio de cursos do SENAI Play.",
    aud: ["empresa"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://business.play.senai.br/", primary: true }] },
  { id: "futuro-digital", cat: "cursos", name: "Futuro.Digital", kicker: "Oferta de cursos",
    desc: "O maior marketplace de Educação Profissional do Brasil: cursos técnicos, de curta e média duração, graduação e pós-graduação, além de certificações e planos de assinatura.",
    aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://www.futuro.digital/", primary: true }, { label: "Conhecer em vídeo", url: "https://www.youtube.com/watch?v=q7-nIogMinE" }] },

  // ---------- Conectar
  { id: "mundo-senai", cat: "eco", name: "Mundo SENAI", kicker: "Cursos, trabalho e carreira", featured: true,
    desc: "Portal de acesso às plataformas do SENAI para conhecer o que a instituição oferece e as oportunidades em Educação Profissional e Superior.",
    aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar portal", url: "https://www.mundosenai.com.br/", primary: true }, { label: "Conhecer em vídeo", url: "https://www.youtube.com/watch?v=m6NUngOFUoQ" }] },
  { id: "meu-senai", cat: "eco", name: "Meu SENAI", kicker: "Ecossistema educacional",
    desc: "Portal de acesso a plataformas e dados para docentes e alunos. Reúne ferramentas para a prática pedagógica, como criar Objetos de Aprendizagem com planilhas, apresentações e formulários dentro de Situações de Aprendizagem classificadas pelo Currículo.",
    aud: ["docente", "aluno"], plat: ["Web"],
    links: [{ label: "Acessar portal", url: "https://meusenai.senai.br/", primary: true }, { label: "Conhecer em vídeo", url: "https://www.youtube.com/watch?v=uC1manEHPxM" }] },

  // ---------- Ensinar
  { id: "itinerarios", cat: "praticas", name: "Itinerários Nacionais", kicker: "Perfis profissionais e desenhos curriculares", featured: true,
    desc: "Ambiente web para desenvolvimento e repositório de perfis profissionais e desenhos curriculares do Itinerário Nacional de Educação Profissional do SENAI, referência para estruturar qualificação, cursos técnicos, superiores de tecnologia, bacharelado e formação inicial e continuada (FIC).",
    aud: ["docente", "gestor"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://itinerario.senai.br/", primary: true }, { label: "Conhecer em vídeo", url: "https://www.youtube.com/watch?v=pIxe90F-Zhk" }] },
  { id: "recursos-didaticos", cat: "praticas", name: "Recursos Didáticos", kicker: "Materiais para suas aulas",
    desc: "Banco de Recursos Didáticos do SENAI: atividades interativas, documentos orientadores e livros didáticos digitais, para apoiar a compreensão dos conceitos teóricos e a realização de atividades práticas.",
    aud: ["docente", "aluno"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://recursosdidaticos.senai.br/", primary: true }, { label: "Conhecer em vídeo", url: "https://youtu.be/sjmQ3Y9a7-A?list=PLPli_KFbLinFjpj4T8VBoZVUwWnPi4jyd" }] },
  { id: "estante", cat: "praticas", name: "Estante de Livros", kicker: "Livros didáticos SENAI",
    desc: "Biblioteca digital com mais de 1200 livros didáticos, com leitura offline dos favoritos. Conta com o Cadu, chatbot que tira dúvidas sobre o conteúdo e gera quizzes interativos. Gratuita, nas versões web e mobile.",
    aud: ["aluno", "docente"], plat: ["Web", "Mobile"],
    links: [{ label: "Acessar plataforma", url: "https://estantedelivros.senai.br/", primary: true }] },
  { id: "canva", cat: "praticas", name: "Canva for Education", kicker: "Criação e colaboração",
    desc: "Professores e alunos do SENAI têm acesso gratuito a ferramentas criativas e colaborativas: planos de aula, infográficos, vídeos, recursos de inteligência artificial e painéis colaborativos. O acesso é feito com a conta SENAI Google.",
    aud: ["docente", "aluno"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://www.canva.com/pt_br/educacao/", primary: true }] },

  // ---------- Avaliar
  { id: "sisbia", cat: "avaliacao", name: "SISBIA", kicker: "Banco de itens de avaliação", featured: true,
    desc: "Banco de Itens de Avaliação do SENAI.", aud: ["docente", "gestor"], plat: ["Web"],
    links: [{ label: "Acessar sistema", url: "https://sisbia.senai.br/login", primary: true }] },
  { id: "siac", cat: "avaliacao", name: "Avaliação de Competências (SIAC)", kicker: "Provas objetivas",
    desc: "Sistema para aplicação de provas objetivas.", aud: ["docente", "aluno"], plat: ["Web"],
    links: [{ label: "Acessar sistema", url: "https://siac.senai.br/login", primary: true }] },
  { id: "navegador-seguro", cat: "avaliacao", name: "Navegador Seguro", kicker: "Proctoring para provas online",
    desc: "Aplicativo de proctoring para provas online.", aud: ["aluno"], plat: ["Desktop"], links: [] },
  { id: "sap", cat: "avaliacao", name: "Avaliação Prática (SAP)", kicker: "Sistema da avaliação prática",
    desc: "Sistema da Avaliação Prática do SENAI.", aud: ["docente"], plat: ["Web"],
    links: [{ label: "Acessar sistema", url: "https://sap.senai.br/login", primary: true }] },
  { id: "saep", cat: "avaliacao", name: "SAEP Resultados", kicker: "Repositório de resultados",
    desc: "Repositório de resultados do SAEP.", aud: ["gestor", "docente"], plat: ["Web"],
    links: [{ label: "Acessar repositório", url: "https://saep.senai.br/", primary: true }] },

  // ---------- Imergir
  { id: "experience", cat: "imersao", name: "SENAI Experience", kicker: "Tecnologias imersivas", featured: true,
    desc: "Porta de entrada para as tecnologias imersivas do SENAI.", aud: ["aluno", "docente"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://experience.senai.br/", primary: true }] },
  { id: "holo-festo", cat: "imersao", name: "Holo SENAI Festo", kicker: "Realidade mista",
    desc: "Experiência de realidade mista para Meta Quest.", aud: ["aluno", "docente"], plat: ["Meta Quest"],
    links: [{ label: "Abrir na Meta", url: "https://www.meta.com/experiences/holosenai-festo/8067150956661352/", primary: true }] },
  { id: "holo-motor", cat: "imersao", name: "Holo SENAI Motor Elétrico", kicker: "Realidade mista",
    desc: "Experiência de realidade mista para Meta Quest.", aud: ["aluno", "docente"], plat: ["Meta Quest"],
    links: [{ label: "Abrir na Meta", url: "https://www.meta.com/pt-br/experiences/8200052170012964/", primary: true }] },
  { id: "nr10", cat: "imersao", name: "Simulador NR10", kicker: "Realidade mista",
    desc: "Simulador de realidade mista para a NR10.", aud: ["aluno", "empresa"], plat: ["Meta Quest"],
    links: [{ label: "Abrir na Meta", url: "https://www.meta.com/pt-br/experiences/simulador-nr10/7922256184533105/", primary: true }, { label: "Recurso didático", url: "https://recursosdidaticos.senai.br/recurso-didatico/18904" }] },
  { id: "siderurgico", cat: "imersao", name: "Universo Siderúrgico", kicker: "Realidade virtual 3D",
    desc: "Experiência em realidade virtual 3D.", aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar recurso", url: "https://recursosdidaticos.senai.br/recurso-didatico/17712", primary: true }] },
  { id: "saep360", cat: "imersao", name: "SAEP 360 Segurança do Trabalho", kicker: "Vídeos 360°",
    desc: "Vídeos 360° de Segurança do Trabalho.", aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar recurso", url: "https://recursosdidaticos.senai.br/recurso-didatico/32125", primary: true }] },
  { id: "tours", cat: "imersao", name: "Tours Virtuais 3D", kicker: "Realidade virtual 3D",
    desc: "Tours virtuais em 3D.", aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://experience.senai.br/", primary: true }] },
  { id: "cnc", cat: "imersao", name: "Simulador CNC", kicker: "Simulador virtual",
    desc: "Simulador virtual de CNC.", aud: ["aluno", "docente"], plat: ["Desktop"],
    links: [{ label: "Baixar simulador", url: "https://drive.google.com/drive/folders/1UfkM6KC2SDTResS7BScfr7kCgn3Gquok?usp=sharing", primary: true }] },
  { id: "space", cat: "imersao", name: "SENAI Space", kicker: "Realidade aumentada",
    desc: "Aplicativo de realidade aumentada do SENAI.", aud: ["aluno", "docente"], plat: ["Android", "iOS"],
    links: [{ label: "Google Play", url: "https://play.google.com/store/apps/details?id=com.SENAI.SenaiSpace", primary: true }, { label: "App Store", url: "https://apps.apple.com/br/app/senai-space/id6444312814" }] },
  { id: "sim-seguranca", cat: "imersao", name: "Segurança do Trabalho", kicker: "Simulador web",
    desc: "Simulador web de Segurança do Trabalho.", aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar simulador", url: "https://recursosdidaticos.senai.br/c/Mjk4NjdSRA==", primary: true }] },
  { id: "sim-moda", cat: "imersao", name: "Produção de Moda", kicker: "Simulador web",
    desc: "Simulador web de Produção de Moda.", aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar simulador", url: "https://recursosdidaticos.senai.br/c/MzAwMDBSRA==", primary: true }] },
  { id: "pintura", cat: "imersao", name: "Pintura Automotiva", kicker: "Game, Meta Quest, metaverso e tour virtual",
    desc: "Experiência de Pintura Automotiva em game, Meta Quest, metaverso e tour virtual.", aud: ["aluno"], plat: ["Web", "Meta Quest"],
    links: [{ label: "Acessar recurso", url: "https://recursosdidaticos.senai.br/c/MjcwOTBSRA==", primary: true }] },
  { id: "rv360", cat: "imersao", name: "RV360 SENAI", kicker: "Realidade virtual",
    desc: "Recurso de realidade virtual 360°.", aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar recurso", url: "https://recursosdidaticos.senai.br/c/Mjk4NjVSRA==", primary: true }] },

  // ---------- Gerir
  { id: "egressos", cat: "gestao", name: "Pesquisa de Egressos", kicker: "Avaliação de efetividade", featured: true,
    desc: "Gestão educacional: avaliação da efetividade da formação a partir de pesquisa com egressos.", aud: ["gestor"], plat: ["Web"],
    links: [{ label: "Acessar sistema", url: "https://sapes.senai.br/login", primary: true }] },
  { id: "lean", cat: "gestao", name: "Sistema Lean", kicker: "Sistema de indicadores",
    desc: "Gestão educacional: sistema de indicadores.", aud: ["gestor"], plat: ["Web"],
    links: [{ label: "Acessar sistema", url: "https://sistemalean.senai.br/", primary: true }] },
  { id: "maturidade", cat: "gestao", name: "Maturidade Digital", kicker: "Plataforma de pesquisas",
    desc: "Plataforma de pesquisas de maturidade digital.", aud: ["empresa", "gestor"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://maturidadedigital.senai.br/", primary: true }] },
  { id: "contrate-me", cat: "gestao", name: "Contrate-me", kicker: "Plataforma de empregos",
    desc: "Plataforma de empregos para egressos e empresas.", aud: ["aluno", "empresa"], plat: ["Web"],
    links: [{ label: "Sou profissional", url: "https://personal.speck.live/contrateme", primary: true }, { label: "Sou empresa", url: "https://business.speck.live/contrateme" }] },
  { id: "recompensas", cat: "gestao", name: "Banco de Recompensas", kicker: "Resgate com SENAI Coins",
    desc: "Resgate suas conquistas utilizando SENAI Coins.", aud: ["aluno"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://bancoderecompensas.senai.br/", primary: true }] },
  { id: "elos", cat: "gestao", name: "Plataforma Elo.S", kicker: "Recompensas do SENAI",
    desc: "Plataforma de recompensas do SENAI.", aud: ["aluno", "docente"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://elos.senai.br/", primary: true }] },

  // ---------- Inovar
  { id: "saga", cat: "inovacao", name: "Plataforma de Inovação (SAGA)", kicker: "Saga SENAI de Inovação", featured: true,
    desc: "Plataforma do Saga SENAI de Inovação.", aud: ["gestor", "empresa"], plat: ["Web"],
    links: [{ label: "Acessar plataforma", url: "https://plataforma.gpinovacao.senai.br/", primary: true }] },
  { id: "worldskills", cat: "inovacao", name: "Gestão da WorldSkills Brasil", kicker: "Seletiva Nacional",
    desc: "Sistema de gestão para a Seletiva Nacional WorldSkills.", aud: ["gestor", "aluno"], plat: ["Web"],
    links: [{ label: "Acessar sistema", url: "https://olimpiada.senai.br/seletivawsc2024/", primary: true }] },

  // ---------- Incluir
  { id: "libras", cat: "assistiva", name: "SENAI LIBRAS", kicker: "Tecnologia assistiva", featured: true,
    desc: "Aplicativo e portal de Língua Brasileira de Sinais do SENAI.", aud: ["aluno", "docente"], plat: ["Web", "Android", "iOS"],
    links: [{ label: "Acessar portal", url: "https://senai-libras.senai.br/", primary: true }, { label: "Google Play", url: "https://play.google.com/store/apps/details?id=com.senailibras" }, { label: "App Store", url: "https://apps.apple.com/br/app/senai-libras/id1480431650" }] }
];
